### ISSUE TITLE
Event-Set combination

### ISSUE THREAD

**Issue by NencioGizuh** [harlyq/aframe-spe-particles-component#1]
I'm using the world relative particle system from the demo. I'm trying to combine it with a event-set component where if you grab the cube that is emiting the particles will be turned on and off. It is not working this is the code I'm trying to use

event-set__grabon="_event: grab-start; spe-particle.enabled: true"
 event-set__graboff="_event: grab-end; spe-particles.enabled: false"

I have tried this with other properties of different components and they didn't work either.

**Comment by harlyq** [comment]
Component names with hyphens (-) are not handled well in AFrame.  AFrame is telling the event-set component that the parameter is speParticles.enabled (notice that the name has changed from kebabCase spe-particles, to camelCase speParticles). 

If you can modify the code, then either change event-set to support the camelCase version of component names, or rename the spe-particles component and remove the hyphen e.g. speparticles
