### ISSUE TITLE
Any chance getting this updated for use with 1.2.0?

### ISSUE THREAD

**Issue by samyH** [harlyq/aframe-spe-particles-component#5]
Currently throws a WebGL based error by the looks of it.

THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog Fragment shader is not compiled.
  THREE.WebGLShader: gl.getShaderInfoLog() fragment
ERROR: 0:246: 'texture' : function name expected
ERROR: 0:246: '=' : dimension mismatch
ERROR: 0:246: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'

**Comment by dirkk0** [comment]
Posted a working example with this fix here:
https://glitch.com/edit/#!/aframe-spe-particles
